Fix issue with spaces in the project path
The path to the preprocessor was being used in the command with surrounding quotes, which lead to it failing when there is a space in the path with errors like this:

```
Test suite failed to run

    Command failed: node --unhandled-rejections=strict --abort-on-uncaught-exception D:\University\Year
4\<long path with more spaces>\node_modules\svelte-jester\dist\preprocess.js
    Uncaught Error: Cannot find module 'D:\University\Year'
```

This should fix the problem and allow for spaces in the path.